apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app
spec:
  selector:
    matchLabels:
      app: iot-app
  replicas: 3
  template:
    metadata:
      labels:
        app: iot-app
    spec:
      nodeSelector:
        env: dev
      containers:
        - name: iot-app
          image: cempassi/iot-app:v2
          ports:
            - containerPort: 5000
              name: iot-app
